language: minimal

os: linux

env:
  global:
    - COVERAGE_STORAGE="json"
    - CONDA_PKGS_DIRS="${HOME}/.cache/conda/pkgs"

matrix:
  fast_finish: true

  include:
    # conda builds
    - name: "conda:3.6"
      env: PYTHON_VERSION="3.6"
    - name: "conda:3.7"
      env: PYTHON_VERSION="3.7"
    - name: "conda:3.8"
      env: PYTHON_VERSION="3.8"
    - name: "conda:3.9"
      env: PYTHON_VERSION="3.9"

before_install:
  - curl -LO https://raw.githubusercontent.com/gwpy/gwpy/master/ci/parse-conda-requirements.py
  - curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - source "${HOME}/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - travis_retry conda update --quiet --yes conda
  # Useful for debugging any issues with conda
  - conda info --all

install:
  # create a conda environment
  - travis_retry conda create --quiet --yes --name gwvetci python=${PYTHON_VERSION} pip setuptools
  - travis_retry conda activate gwvetci
  - travis_retry python ./parse-conda-requirements.py requirements.txt -o conda-reqs.txt
  - travis_retry conda install --quiet --yes --update-all --name gwvetci --file conda-reqs.txt
  # clean up
  - rm -f conda-reqs.txt parse-conda-requirements.py
  # install this version
  - python -m pip install .

script:
  # run flake8
  - python -m flake8 .
  # test executables
  - python -m coverage run --append --source gwvet -m gwvet --help
  - python -m coverage run --append --source gwvet -m gwvet.hug --help
  - python -m coverage run --append --source gwvet -m gwvet.vdf --help

before_cache:
  - travis_retry conda clean --quiet --yes --all
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  pip: true
  directories:
    - ${HOME}/.cache/conda/pkgs
